<a href="index.php?gene=MAGEA10">MAGEA10</a><br>
<a href="index.php?gene=MAGEA11">MAGEA11</a><br>
<a href="index.php?gene=MAGEA2">MAGEA2</a><br>
<a href="index.php?gene=MAGEA2B">MAGEA2B</a><br>
<a href="index.php?gene=MAGEA4">MAGEA4</a><br>
<a href="index.php?gene=MAGEA6">MAGEA6</a><br>
<a href="index.php?gene=MAGEA1">MAGEA1</a><br>
<a href="index.php?gene=MAGEA12">MAGEA12</a><br>
<a href="index.php?gene=MAGEA3">MAGEA3</a><br>
<a href="index.php?gene=MAGEA5">MAGEA5</a><br>
<a href="index.php?gene=MAGEA8">MAGEA8</a><br>
<a href="index.php?gene=MAGEA9">MAGEA9</a><br>
<a href="index.php?gene=MAGEE1">MAGEE1</a><br>
<a href="index.php?gene=MAGEE2">MAGEE2</a><br>
<a href="index.php?gene=SPANXA2">SPANXA2</a><br>
<a href="index.php?gene=SPANXE">SPANXE</a><br>
<a href="index.php?gene=SPANXN1">SPANXN1</a><br>
<a href="index.php?gene=SPANXN2">SPANXN2</a><br>
<a href="index.php?gene=SPANXN3">SPANXN3</a><br>
<a href="index.php?gene=SPANXN4">SPANXN4</a><br>
<a href="index.php?gene=SPANXN5">SPANXN5</a><br>
<a href="index.php?gene=SPANXA1">SPANXA1</a><br>
<a href="index.php?gene=SPANXB1">SPANXB1</a><br>
<a href="index.php?gene=SPANXC">SPANXC</a><br>
<a href="index.php?gene=SPANXD">SPANXD</a><br>
<a href="index.php?gene=XAGE1">XAGE1</a><br>
<a href="index.php?gene=XAGE2">XAGE2</a><br>
<a href="index.php?gene=XAGE3">XAGE3</a><br>
<a href="index.php?gene=XAGE5">XAGE5</a><br>
<a href="index.php?gene=DDX43">DDX43</a><br>
<a href="index.php?gene=SAGE1">SAGE1</a><br>
<a href="index.php?gene=ADAM2">ADAM2</a><br>
<a href="index.php?gene=PAGE1">PAGE1</a><br>
<a href="index.php?gene=PAGE2">PAGE2</a><br>
<a href="index.php?gene=PAGE3">PAGE3</a><br>
<a href="index.php?gene=PAGE4">PAGE4</a><br>
<a href="index.php?gene=PAGE5">PAGE5</a><br>
<a href="index.php?gene=PAGE2B">PAGE2B</a><br>
<a href="index.php?gene=LIPI">LIPI</a><br>
<a href="index.php?gene=IL13RA1">IL13RA1</a><br>
<a href="index.php?gene=BAGE">BAGE</a><br>
<a href="index.php?gene=BAGE2">BAGE2</a><br>
<a href="index.php?gene=BAGE3">BAGE3</a><br>
<a href="index.php?gene=BAGE4">BAGE4</a><br>
<a href="index.php?gene=BAGE5">BAGE5</a><br>
<a href="index.php?gene=TSP50">TSP50</a><br>
<a href="index.php?gene=CTAGE5">CTAGE5</a><br>
<a href="index.php?gene=CTAGE1">CTAGE1</a><br>
<a href="index.php?gene=SPA17">SPA17</a><br>
<a href="index.php?gene=ACRBP">ACRBP</a><br>
<a href="index.php?gene=CSAG1">CSAG1</a><br>
<a href="index.php?gene=CSAG2">CSAG2</a><br>
<a href="index.php?gene=DSCR8">DSCR8</a><br>
<a href="index.php?gene=DDX53">DDX53</a><br>
<a href="index.php?gene=CTCFL">CTCFL</a><br>
<a href="index.php?gene=LUZP4">LUZP4</a><br>
<a href="index.php?gene=CASC5">CASC5</a><br>
<a href="index.php?gene=MAGEB1">MAGEB1</a><br>
<a href="index.php?gene=MAGEB3">MAGEB3</a><br>
<a href="index.php?gene=MAGEB4">MAGEB4</a><br>
<a href="index.php?gene=MAGEB2">MAGEB2</a><br>
<a href="index.php?gene=MAGEB5">MAGEB5</a><br>
<a href="index.php?gene=MAGEB6">MAGEB6</a><br>
<a href="index.php?gene=TFDP3">TFDP3</a><br>
<a href="index.php?gene=JARID1B">JARID1B</a><br>
<a href="index.php?gene=LDHC">LDHC</a><br>
<a href="index.php?gene=MORC1">MORC1</a><br>
<a href="index.php?gene=DKKL1">DKKL1</a><br>
<a href="index.php?gene=SPO11">SPO11</a><br>
<a href="index.php?gene=CRISP2">CRISP2</a><br>
<a href="index.php?gene=FMR1NB">FMR1NB</a><br>
<a href="index.php?gene=NFX1">NFX1</a><br>
<a href="index.php?gene=NXF2">NXF2</a><br>
<a href="index.php?gene=GAGE1">GAGE1</a><br>
<a href="index.php?gene=GAGE7B">GAGE7B</a><br>
<a href="index.php?gene=GAGE2">GAGE2</a><br>
<a href="index.php?gene=GAGE4">GAGE4</a><br>
<a href="index.php?gene=GAGE5">GAGE5</a><br>
<a href="index.php?gene=GAGE7">GAGE7</a><br>
<a href="index.php?gene=GAGE8">GAGE8</a><br>
<a href="index.php?gene=TAF7L">TAF7L</a><br>
<a href="index.php?gene=TDRD1">TDRD1</a><br>
<a href="index.php?gene=TDRD6">TDRD6</a><br>
<a href="index.php?gene=TEX15">TEX15</a><br>
<a href="index.php?gene=FATE1">FATE1</a><br>
<a href="index.php?gene=TPTE">TPTE</a><br>
<a href="index.php?gene=CT45-2">CT45-2</a><br>
<a href="index.php?gene=CT45-3">CT45-3</a><br>
<a href="index.php?gene=HORMAD1">HORMAD1</a><br>
<a href="index.php?gene=CT47">CT47</a><br>
<a href="index.php?gene=SLCO6A1">SLCO6A1</a><br>
<a href="index.php?gene=SSX5">SSX5</a><br>
<a href="index.php?gene=SSX6">SSX6</a><br>
<a href="index.php?gene=SSX7">SSX7</a><br>
<a href="index.php?gene=SSX9">SSX9</a><br>
<a href="index.php?gene=SSX1">SSX1</a><br>
<a href="index.php?gene=SSX2">SSX2</a><br>
<a href="index.php?gene=SSX3">SSX3</a><br>
<a href="index.php?gene=SSX4">SSX4</a><br>
<a href="index.php?gene=LEMD1">LEMD1</a><br>
<a href="index.php?gene=HSPB9">HSPB9</a><br>
<a href="index.php?gene=ZNF165">ZNF165</a><br>
<a href="index.php?gene=SPACA3">SPACA3</a><br>
<a href="index.php?gene=CXorf48">CXorf48</a><br>
<a href="index.php?gene=THEG">THEG</a><br>
<a href="index.php?gene=ACTL8">ACTL8</a><br>
<a href="index.php?gene=COX6B2">COX6B2</a><br>
<a href="index.php?gene=CTAG1A">CTAG1A</a><br>
<a href="index.php?gene=CTAG2">CTAG2</a><br>
<a href="index.php?gene=CTAG1B">CTAG1B</a><br>
<a href="index.php?gene=CCDC33">CCDC33</a><br>
<a href="index.php?gene=PASD1">PASD1</a><br>
<a href="index.php?gene=TULP2">TULP2</a><br>
<a href="index.php?gene=CT66">CT66</a><br>
<a href="index.php?gene=KLKBL4">KLKBL4</a><br>
<a href="index.php?gene=MGC27016">MGC27016</a><br>
<a href="index.php?gene=CT69">CT69</a><br>
<a href="index.php?gene=MAGEC2">MAGEC2</a><br>
<a href="index.php?gene=MAGEC1">MAGEC1</a><br>
<a href="index.php?gene=MAGEC3">MAGEC3</a><br>
<a href="index.php?gene=CT70">CT70</a><br>
<a href="index.php?gene=SPINLW1">SPINLW1</a><br>
<a href="index.php?gene=TSSK6">TSSK6</a><br>
<a href="index.php?gene=ADAM29">ADAM29</a><br>
<a href="index.php?gene=CCDC36">CCDC36</a><br>
<a href="index.php?gene=SYCE1">SYCE1</a><br>
<a href="index.php?gene=CPXCR1">CPXCR1</a><br>
<a href="index.php?gene=TSPY1">TSPY1</a><br>
<a href="index.php?gene=TSGA10">TSGA10</a><br>
<a href="index.php?gene=SYCP1">SYCP1</a><br>
<a href="index.php?gene=PIWIL2">PIWIL2</a><br>
<a href="index.php?gene=ARMC3">ARMC3</a><br>
<a href="index.php?gene=AKAP3">AKAP3</a><br>
<a href="index.php?gene=PBK">PBK</a><br>
<a href="index.php?gene=C21orf99">C21orf99</a><br>
<a href="index.php?gene=OIP5">OIP5</a><br>
<a href="index.php?gene=CEP290">CEP290</a><br>
<a href="index.php?gene=CABYR">CABYR</a><br>
<a href="index.php?gene=SPAG9">SPAG9</a><br>
<a href="index.php?gene=BRDT">BRDT</a><br>
<a href="index.php?gene=MPHOSPH1">MPHOSPH1</a><br>
<a href="index.php?gene=RSPH1">RSPH1</a><br>
<a href="index.php?gene=CCDC110">CCDC110</a><br>
<a href="index.php?gene=CXorf61">CXorf61</a><br>
<a href="index.php?gene=NLRP4">NLRP4</a><br>
